### PR TITLE
Add python 3.3.6 grammar specification.

### PR DESCRIPTION
**Pull request by b5y**
Add python 3.3.6 grammar specification. Rename specification for python 2.

### CODE REVIEW

**Comment by Psycojoker** [comment]
Actually, what we need here is to do a merge between python 2.7 grammar and python 3.6 which will require some manual work.

A good way to start this work is simply to do a `vimdiff` (or any other diff tool) of both grammar then starting to merge then. This is not an easy work and we probably should document our choice.

Here is a screenshot as an example:

2016-08-15-124743_1674x1036_scrot

**Comment by b5y** [comment]
Got it. Thank you for response. 
If I understand correctly, we should document it on separate page explaining every line in merging.

**Comment by alexbw** [comment]
What's the status of Python 3.x support? Considering this tool for a project of mine, just want to get a sense of if it is still maintained.

**Comment by boxed** [comment]
@Psycojoker Why do we need to do the merge? Shouldn't the grammars be different and separate... since they are?

**Comment by Psycojoker** [comment]
Started working on a roadmap/checklist of the diff between python 2.7 grammar and python 3.6 here https://baron.readthedocs.io/en/latest/grammar.html because I want to keep track of the evolution and the decisions takens. Job is done for python 3.3 for now, I'll continue later to move to 3.6 and then I'll start merging all the grammar PR while updating it.

Right now the visual result/UX on readthedocs is kinda quite bad, maybe I'll fiddle a bit with the theme to improve it or something like that.

I'll probably do a pseudo-grammar file which will be a more or less accurate representation of what grammar baron follows.

cc @odcinek

Thanks for your contributions :)

**Comment by boxed** [comment]
Great to hear this is going forward!

**Comment by Psycojoker** [comment]
Update, job done for 3.6. I should be starting to merge soon if I don't encounter any problems.

**Pull request merged**
