### PR TITLE
Speed up has_print_function.

### PR DESCRIPTION
**Pull request by duncf**
This speeds up parsing significantly for large files.

### CODE REVIEW

**Comment by Psycojoker** [comment]
Oh, sound like a good thing :)

I've never took the time to optimize baron so you'll probably find other things like that lying around :/

Thanks!

**Comment by Psycojoker** [comment]
Oh, and after a quick test that reduce parse time (on baron's own code) by 38%, pretty nice :+1:

**Comment by duncf** [comment]
I profiled parsing a pretty large file with RedBaron, and this was ~75%. I didn't see any other low hanging fruit, but I didn't look into it that closely. Thanks for accepting the pull request!

**Comment by Psycojoker** [comment]
That sound like a really big file. Are you in a position where you can give me some details on what you've been doing? I'm always eager to learn how people are using red/baron :)

**Comment by duncf** [comment]
I'm mostly just playing with RedBaron right now -- small refactorings, etc. Nothing too exciting, sorry. :-)

**Pull request merged**
