### PR TITLE
PEP484 support and bugfixes

### PR DESCRIPTION
**Pull request by kyleatmakrs**
This allows baron to parse files with PEP484 type annotations.

Also a bugfix for handling endl inside groups:
"(a
  [0])"

### CODE REVIEW

**Comment by boxed** [comment]
How is this PR different from https://github.com/PyCQA/baron/pull/115 ? I'm trying to make a fork of baron with all the open PRs and it seems these two PRs overlap..

**Comment by kyleatmakrs** [comment]
No difference.  I didn't see that before submitting this PR.

**Comment by boxed** [comment]
Cool. Then I’ll use the other one for my fork.

**Comment by Psycojoker** [comment]
Merge by hand, thx a lot :)

**Pull request closed without merging**
