### PR TITLE
Add yield from supporting

### PR DESCRIPTION
**Pull request by b5y**

### CODE REVIEW

**Comment by ibizaman** [comment]
Nice, LGTM! Just waiting for @Psycojoker's approval to merge this.

**Comment by b5y** [comment]
Thanks!
This PR is under development. It is not finished yes. I will proceed my work on it soon.

**Comment by ibizaman** [comment]
@b5y oh okay no worries :) thanks!

**Comment by boxed** [comment]
@b5y What's left to do?

**Comment by Psycojoker** [comment]
Hello,

The parser generator part is missing here (in the `grammar_*` files).

**Comment by Psycojoker** [comment]
Merged here https://github.com/PyCQA/baron/pull/113

**Pull request closed without merging**
